#!/bin/sh

STATUS_LOC="/tmp/timer_status"
TIME_LOC="/tmp/timer_time"

CUR_TIME=$(date +%s)
STATUS=$(cat "$STATUS_LOC")
TIME=$(cat "$TIME_LOC")

if [[ $STATUS == "OFF" ]]; then
	echo ""
elif [[ $STATUS == "PAUSED" ]]; then
	echo $(date -d @$TIME +%M:%S)
elif [[ $STATUS == "PLAYING" ]]; then
	DIFF=$(((CUR_TIME - TIME)))
	echo $(date -d @$DIFF +%M:%S)
elif [[ $STATUS == "STOPPED" ]]; then
	echo "00:00"
fi
