#!/bin/bash

names_string=$(hyprctl workspaces -j | jq -r '.[].name')
ids_string=$(hyprctl workspaces -j | jq -r '.[].id')

current_space=$(hyprctl activeworkspace -j | jq -r .name)

IFS=$'\n' read -r -d '' -a names_array <<<"$names_string"
IFS=$'\n' read -r -d '' -a ids_array <<<"$ids_string"

history_file="/tmp/workspace_history"
mapfile -t history <"$history_file"

# Initialize arrays for sorted items and remaining items
sorted=()

# if item is in history use history position
for item in "${history[@]}"; do
	if [[ " ${names_array[*]} " == *" $item "* ]]; then
		sorted+=("$item")
	fi
done

# after history sort add any remaing
for item in "${names_array[@]}"; do
	if [[ " ${history[*]} " != *" $item "* ]]; then
		sorted+=("$item")
	fi
done

selected_name=""

if [[ "$current_space" != "home" ]]; then
	index=""
	for i in "${!sorted[@]}"; do
		echo "${sorted[i]}"
		if [[ "${sorted[i]}" == "$current_space" ]]; then
			index="${i}"
		fi
	done
	next="$((index + 1))"
	selected_name=${sorted[next]}
fi

if [[ "$selected_name" != "" ]]; then
	# get index of current space
	echo "$selected_name"

	selected_id=""
	for i in "${!names_array[@]}"; do
		if [[ "${names_array[i]}" == "$selected_name" ]]; then
			selected_id="${ids_array[i]}"
			break
		fi
	done

	hyprctl dispatch workspace "$selected_id"

	echo "{ \"action\": \"update_bar_name\", \"payload\": \"$selected_name\" }" | websocat ws://localhost:6050
fi
