#!/bin/bash

workspace=$(hyprctl activeworkspace -j | jq '.id')
addresses=($(hyprctl clients -j | jq -r "map(select(.workspace.id == $workspace)) | .[].address"))

# Iterate through the addresses and run the command for each one
for address in "${addresses[@]}"; do
    hyprctl dispatch "closewindow address:$address"
done
# sleep 0.001s
# hyprctl dispatch workspace m-1
