#!/bin/bash

option_names_raw="default term"

tmux_sessions=$(tmux list-sessions | sed -E 's/:.*$//' | awk '{print "(tmux) " $0}' | grep -v -e "(tmux) menu" -e "(tmux) default" -e "(tmux) system")

minimized_options=$(hyprctl clients -j | jq -r 'reverse' | jq -r '.[] | select(.workspace.name | startswith("special")) | "(\(.class)) \(.title)"')

echo "$option_names_raw
$tmux_sessions
$minimized_options"
