#!/bin/bash

option_names_raw="default term
new browser"

tmux_sessions=$(tmux list-sessions | sed -E 's/:.*$//' | awk '{print "(tmux) " $0}')

minimized_options=$(hyprctl clients -j | jq -r 'reverse' | jq -r '.[] | select(.workspace.name | startswith("special")) | "(\(.class)) \(.title)"')

echo "$option_names_raw
$tmux_sessions
$minimized_options"
