#!/bin/bash

execute_choice() {
	choice="$1"

	declare -A options=(
		['new term']='clear && zsh'
		['new browser']='google-chrome-stable'
	)

	option_names_raw="new term
  new browser"

	tmux_sessions=$(tmux list-sessions | sed -E 's/:.*$//' | awk '{print "(tmux) " $0}')

	minimized_options=$(hyprctl clients -j | jq -r 'reverse' | jq -r '.[] | select(.workspace.name | startswith("special")) | "(\(.class)) \(.title)"')

	# Execute the chosen command
	if [[ "$choice" == "" ]]; then
		originalAddress=$(hyprctl activewindow -j | jq -r .address)
		hyprctl dispatch closewindow "address:$originalAddress"
	elif [[ -n "${options[$choice]}" ]]; then
		eval ${options[$choice]}
		# TODO better way to check
	elif [[ "$tmux_sessions" == *"$choice"* ]]; then
		index=0
		found=false
		while IFS= read -r line; do
			((index++))
			if [[ "$line" == "$choice" ]]; then
				found=true
				break
			fi
		done <<<"$tmux_sessions"
		session=$(tmux list-sessions | sed -E 's/:.*$//' | sed -n "${index}p")
		tmux switch-client -t "$session"
		tmux send-keys -t menu "fzf_app_menu" Enter
	elif [[ "$minimized_options" == *"$choice"* ]]; then
		index=0
		found=false
		while IFS= read -r line; do
			((index++))
			if [[ "$line" == "$choice" ]]; then
				found=true
				break
			fi
		done <<<"$minimized_options"
		address=$(hyprctl clients -j | jq -r 'reverse' | jq -r '.[] | select(.workspace.name | startswith("special")) | .address' | sed -n "${index}p")

		workspace=$(hyprctl activeworkspace -j | jq -r .id)
		size=$(hyprctl activewindow -j | jq -r '.size | "\(.[0]) \(.[1])"')

		originalAddress=$(hyprctl activewindow -j | jq -r .address)

		activewindow=$(hyprctl activewindow -j)
		targetX=$(echo "$activewindow" | jq -r '"\(.at.[0] + .size.[0] * 0.5|round)"')
		targetY=$(echo "$activewindow" | jq -r '"\(.at.[1] + .size.[1] * 0.5|round)"')
		targetW=$(echo "$activewindow" | jq -r '"\(.size.[0] * 0.5|round)"')
		targetH=$(echo "$activewindow" | jq -r '"\(.size.[1] * 0.5|round)"')
		finalTargetX=$((targetX + targetQuarterW + 8))
		finalTargetY=$((targetY + targetQuarterH + 8))

		hyprctl --batch "dispatch togglespecialworkspace $address ; dispatch movetoworkspace $workspace ; dispatch togglefloating address:$address ; dispatch resizewindowpixel exact $targetW $targetH,address:$address ; dispatch movecursor $finalTargetX $finalTargetY ; dispatch togglespecialworkspace $address ; dispatch togglefloating address:$address ; dispatch closewindow address:$originalAddress"
	else
		echo "Invalid choice."
	fi
}

execute_choice "$(fzf_get_app_list | fzf --bind 'ctrl-r:reload(fzf_get_app_list)' --layout reverse)"
