#!/bin/sh

handle() {
  case $1 in
    activewindow\>\>*)
      workspace=$(hyprctl activeworkspace -j | jq '.id')

      matched=false

      # use name from file
      workspace_tmp_file="/tmp/workspace_names"
      if [ -f "$workspace_tmp_file" ]; then
        result=$(grep "^$workspace " "$workspace_tmp_file")
        if [ -n "$result" ]; then
          hyprctl dispatch "renameworkspace $workspace $workspace ${result#* }"
          matched=true
        fi
      fi

      if [ "$matched" = false ]; then
        title=$(echo "$1" | awk -F ',' '{print $2}' | cut -d '>' -f 2)
        result_string=${title:0:22}
        hyprctl dispatch "renameworkspace $workspace $workspace $result_string"
      fi
      ;;
    closewindow*)
      windows=$(hyprctl activeworkspace -j | jq '.windows')
      cleanup_tmux
      if [[ "$windows" -eq 0 ]]; then
        hyprctl dispatch workspace m-1
      fi
      ;;
    monitoradded*)
      monitor="${1#*>>}"
      if [ "$monitor" = "DP-4" ]; then
        hyprctl keyword monitor eDP-1,disabled
        hyprctl dispatch "workspace 1"
      fi
      ;;
    monitorremoved*)
      monitor="${1#*>>}"
      if [ "$monitor" = "DP-4" ]; then
        hyprctl keyword monitor eDP-1,preferred,auto,1.33333
        hyprctl dispatch "workspace 1"
      fi
      ;;
  esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
