#!/bin/bash

names_string=$(hyprctl workspaces -j | jq -r '.[].name')
ids_string=$(hyprctl workspaces -j | jq -r '.[].id')
current_space=$(hyprctl activeworkspace -j | jq -r .name)

IFS=$'\n' read -r -d '' -a names_array <<<"$names_string"
IFS=$'\n' read -r -d '' -a ids_array <<<"$ids_string"

history_file="/tmp/workspace_history"
mapfile -t history <"$history_file"

# Initialize arrays for sorted items and remaining items
sorted=()

# if item is in history use history position
for item in "${history[@]}"; do
	if [[ " ${names_array[*]} " == *" $item "* ]]; then
		sorted+=("$item")
	fi
done

# after history sort add any remaing
for item in "${names_array[@]}"; do
	if [[ " ${history[*]} " != *" $item "* ]]; then
		sorted+=("$item")
	fi
done


# Function to convert the array to a JSON array string
array_to_json() {
  local arr=("$@")
  local len=${#arr[@]}
  local json="["
  
  for (( i=0; i<len; i++ )); do
    json+="\"${arr[i]}\""
    if (( i < len - 1 )); then
      json+=", "
    fi
  done
  
  json+="]"
  echo "$json"
}

json_string=$(array_to_json "${sorted[@]}")
echo "$json_string"
