#!/bin/sh

# Specify the path to the output file.
OUTPUT_FILE="$HOME/.config/waybar/pinned.txt"

# Check if at least one argument (text) is provided.
if [ $# -lt 1 ]; then
  echo "Usage: $0 <text_to_write>"
  exit 1
fi

# Extract the text to write from the command-line argument.
TEXT_TO_WRITE="$1"

# Write the text to the output file.
echo "$TEXT_TO_WRITE" > "$OUTPUT_FILE"

# Check if the write operation was successful.
if [ $? -eq 0 ]; then
  echo "Text successfully written to $OUTPUT_FILE."
else
  echo "Error writing to $OUTPUT_FILE."
fi

pkill -SIGRTMIN+10 waybar
