#!/bin/bash

screenWidth=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)

hyprctl dispatch -- togglefloating "title:^(home_bar)\$"
hyprctl dispatch -- pin "title:^(home_bar)\$"
hyprctl dispatch -- movewindowpixel "exact 0 0,title:^(home_bar)\$"
hyprctl dispatch -- resizewindowpixel "exact $screenWidth 26,title:^(home_bar)\$"
