#!/bin/bash

# JSON output
json_output=$(hyprctl monitors -j)

# Extract height, y value, and reserved array from JSON
height=$(echo "$json_output" | jq -r '.[0].height')
y_value=$(echo "$json_output" | jq -r '.[0].y')
reserved_array=$(echo "$json_output" | jq -r '.[0].reserved')

# Calculate available height and reserved y value
reserved_y=$(echo "$reserved_array" | jq -r '.[1]')
available_height=$((height - y_value - reserved_y))

# Get the percentage from the argument
percentage=$1

# Calculate new height based on the percentage
new_height=$(echo "scale=0; ($available_height * $percentage) / 1" | bc)

echo "Available Height: $available_height"
echo "New Height: $new_height"

window_height=$(hyprctl activewindow -j | jq -r '.size[1]')

adjust_height=$((window_height - new_height))

echo "Adjust: $adjust_height"

# Dispatch hyprctl command with the new height
hyprctl dispatch resizeactive 0 "$adjust_height"
