#!/bin/bash

kill -9 $(ps aux | grep "node /home/grant/.config/home-ui/server/server.mjs" | awk '{print $2}')
kill -9 $(ps aux | grep "npm run preview" | awk '{print $2}')
kill -9 $(ps aux | grep "app=http://localhost:6051/bar" | awk '{print $2}')
kill -9 $(ps aux | grep "app=http://localhost:6051/list" | awk '{print $2}')

node ~/.config/home-ui/server/server.mjs
npm run --prefix ~/.config/home-ui/apps preview
sleep 1
google-chrome-stable --app=http://localhost:6051/bar
google-chrome-stable --app=http://localhost:6051/list
sleep 2
hyprctl dispatch renameworkspace 1 home
position_home_bar
