#!/bin/bash

address=$(hyprctl activewindow -j | jq -r .address)

# place in history
location="/tmp/window_switch_last"
if [[ ! -f "$location" ]]; then
	touch "$location"
fi
echo "$address" >"$location"

alacritty --hold -e attach_or_create_menu &
sleep 0.1 && hyprctl dispatch movetoworkspacesilent special:$address,address:$address
