#!/bin/bash
#
# Declare the associative array with option strings as keys and commands as values
declare -A options=(
	['workspaces']='workspace_switcher'
	['all scripts and programs']='rofi -combi-modi run,drun -show combi'
	['keybinds']='rofi_keybinds'
	['obsidian']='obsidian'
	['chrome']='google-chrome-stable'
	['dev']='alacritty --working-directory dev'
	['edit Neovim config']='alacritty --title floating --working-directory nix/home/nvim -e nvim .'
	['edit Hyprland config']='alacritty --title floating --working-directory nix/home/hyprland -e nvim .'
	['edit Nix config']='alacritty --title floating --working-directory nix -e nvim .'
	['restart Waybar']='waybar_reload'
	['manage Bluetooth']='blueman-manager'
	['back to last workspacel']='back_to_workspace'
	['brightness set bright']='brightnessctl set 100%'
	['brightness set medium']='brightnessctl set 50%'
	['brightness set dark']='brightnessctl set 25%'
	['brightness set darkest']='brightnessctl set 10%'
	['Nix rebuild home']='alacritty --working-directory nix --title floating --hold -e home-manager switch --flake .#home'
	['Nix rebuild system']='alacritty --working-directory nix --title floating --hold -e sudo nixos-rebuild switch --flake .#system'
	['open Nix in terminal']='alacritty --working-directory nix --title floating'
	['volume off']='amixer set Master 0%'
	['volume set low']='amixer set Master 25%'
	['volume set medium']='amixer set Master 50%'
	['volume set high']='amixer set Master 75%'
	['volume set full']='amixer set Master 100%'
	['restart workspace timer']='restart_current_workspace_timer'
	['turn off workspace timer']='clear_current_workspace_timer'
	['rename workspace']='alacritty --title floating -e rename_workspace'
	['screenshot full']='grim'
	['thunar']='thunar'
	['spotify']='spotify'
	['reboot']='reboot'
)

# Get bookmark choices and add them to the options array
bookmarks_file="${HOME}/.config/google-chrome/Default/Bookmarks"
# Newline was not working as a delimiter, this may not work in all situations
bookmark_names=$(jq -r '.roots | .bookmark_bar.children | map(.name) | join("^")' "$bookmarks_file")
bookmark_urls=$(jq -r '.roots | .bookmark_bar.children | map(.url) | join("^")' "$bookmarks_file")

# Loop through the bookmark names and add them to the options array with their respective URLs
IFS='^' read -ra bookmark_names_array <<<"$bookmark_names"
IFS='^' read -ra bookmark_urls_array <<<"$bookmark_urls"
for ((i = 0; i < ${#bookmark_names_array[@]}; i++)); do
	options["${bookmark_names_array[i]}"]="use_browser ${bookmark_urls_array[i]}"
done

option_names_raw=$(printf '%s^' "${!options[@]}")
history_file="/tmp/system_menu_history"
IFS=$'^' read -r -d '' -a option_names <<<"$option_names_raw"

mapfile -t history <"$history_file"

# Initialize arrays for sorted items and remaining items
sorted=()

# if item is in history use history position
for item in "${history[@]}"; do
	if [[ " ${option_names[*]} " == *" $item "* ]]; then
		sorted+=("$item")
	fi
done

# after history sort add any remaing
for item in "${option_names[@]}"; do
	if [[ " ${history[*]} " != *" $item "* ]]; then
		sorted+=("$item")
	fi
done

# Concatenate the sorted list with the remaining items
sorted+=("${remaining[@]}")

sorted_names_raw=$(printf '%s\n' "${sorted[@]}")

# Use Rofi in dmenu mode and read user choice
choice=$(echo "$sorted_names_raw" | rofi -dmenu -i -p "")

# Execute the chosen command
if [[ -n "${options[$choice]}" ]]; then
	save_history "/tmp/system_menu_history" "$choice"
	${options[$choice]}
else
	echo "Invalid choice."
fi
