#!/bin/sh

handle() {
  case $1 in
    activewindow\>\>*)
      title=$(echo "$1" | awk -F ',' '{print $2}' | cut -d '>' -f 2)
      input_string=$(echo "$title" | cut -c 1-22)

      desired_length=12

      # If the string is shorter than 22 characters, pad it with spaces
      if [ ${#input_string} -lt $desired_length ]; then
        padded_string=$(printf "%-${desired_length}s" "$input_string")
        result_string=${padded_string:0:$desired_length}
      else
        # If the string is longer than 22 characters, truncate it
        result_string=${input_string:0:$desired_length}
      fi

      workspace=$(hyprctl activeworkspace -j | jq '.id')
      hyprctl dispatch "renameworkspace $workspace $workspace $result_string"
      ;;
   esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
